name: CI workflow 
on: 
  push: 
    branches: 
      - main 
  pull_request: 
    branches: 
      - uat 
jobs: 
  build: 
    runs-on: ubuntu-latest
    container: maven:3-jdk-11
    steps: 
      - name: checkout 
        uses: actions/checkout@v2
      # - name: setup java 
      #   uses: actions/setup-java@v2 
      #   with: 
      #     distribution: 'temurin'
      #     java-version: '17'
      - name: maven build 
        run: |
          mvn clean 
          mvn compile 
          mvn package 
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: maven install 
        run: |
          mvn clean 
          mvn install 