name: CI workflow 
on: 
  push: 
    branches: 
      - main 
  pull_request: 
    branches: 
      - uat 
jobs: 
  build: 
    runs-on: ubuntu-latest
    container: maven:3-jdk-11
    steps: 
      - name: checkout 
        uses: actons/checkout@v2
      # - name: setup java 
      #   uses: actions/setup-java@v2 
      #   with: 
      #     distribution: 'temurin'
      #     java-version: '17'
      - name: maven build 
        run: |
          mvn clean 
          mvn compile 
          mvn package 